# Generated by Django 2.2.3 on 2019-10-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelname',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='modelname',
            name='Lastname',
        ),
    ]
